version: '3'

services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_DATABASE: vuttr
    ports:
      - "27017:27017"

networks:
  mongo-compose-network:
    driver: bridge
