version: '3'

services:
  app:
    build: ../
    ports:
      - '3000:3000'
    command: yarn start

  mysqlsrv:
    image: mysql
    ports:
      - '3306:3306'
    restart: always
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_DATABASE: 'vuttr'
    depends_on:
      - app

  mongo:
    image: mongo
    ports:
      - '27017:27017'
    restart: always
    environment:
      MONGO_INITDB_DATABASE: vuttr
    depends_on:
      - app
